comedy-rss does not use getopt

diff --git a/comedy-rss b/comedy-rss
--- a/comedy-rss
+++ b/comedy-rss
@@ -1,38 +1,36 @@
 #!/bin/sh
-
-while getopts "hb:i:" opt; do
-  case $opt in
-    b)
-      BASE_URL=$OPTARG
-      ;;
-    i)
-      INPUT_HTML=$OPTARG
-      ;;
-    h)
-     cat <<EOF
-Usage: ./comedy-rss -b http://base/url/of/your/directory -i parse_this.html [-h]
-
-Create rss file from the jpg link of the input html file. The jpeg files are handled as local files.
-The name of the rss file will be created from the input file with extension replacement (html->rss).
+if [ "$1" = "-h" ]; then
+cat <<EOF
+Usage: ./comedy-rss [-h] -b <dir-url> -i <input-html>
 
 Options:
-  h  print this help and exit
-  b  url of the working directory
-     $BASE_URL environment variable can be used instead of it
-  i  input html file
-     $INPUT_HTML environment variable can be used instead of it
+  -h              print this help and exit
+  -b <dir-url>    url of the working directory
+                  $BASE_URL environment variable can be used instead
+  -i <input-html> input file to parse
+                  $INPUT_HTML environment variable can be used instead
+
+Create rss file from jpg links in the input html file. 
+The jpg files are handled as local files.
+The rss file's name reflects the input file, with extension changed to rss.
 EOF
-     exit 0
-     ;;
-   \?)
-      echo "Invalid option: -$OPTARG" > /dev/null
-      exit 1
-      ;;
-   :) 
-      echo "Option -$OPTARG requires an argument." > /dev/null
-      exit 1
-      ;;
-  esac
+exit 0
+fi
+
+while [ -n "$*" ]; do
+  if [ "$1" = "-b" ]; then
+    shift
+    BASE_URL=$1
+    shift
+  fi
+  if [ "$1" = "-i" ]; then
+    shift
+    INPUT_HTML=$1
+    shift
+  else
+    echo >&2 "Invalid option: $1"
+    shift
+  fi
 done
 
 FILE=`echo ${INPUT_HTML%.*}.rss`
